version: "3.3"
services:
  nginx:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    container_name: nginx-rtmp-kvs
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        ENABLED_MODULES: rtmp
        KVS_SDK_VERSION: 3.2.0
    ports:
      - "1935:1935"
